### PR TITLE
enh: fetch all available channels + cache + fixes

### LINKED ISSUE #8: [bug] not all channels are displayed
it would be probably helpful to describe which permissions are necessary.
As the channels are neither sorted nor searchable, I can not determine wich channels are missing.
I am sure that not all public channels are listed, nor my private ones.
May be this is also a Slack app configuration issue.

Slack-NC App can:
 View information about a user’s identity, granted by 1 team member
 View basic information about public channels in a workspace, granted by 1 team member
 View basic information about a user’s private channels, granted by 1 team member
 View basic information about a user’s direct messages, granted by 1 team member
 View basic information about a user’s group direct messages, granted by 1 team member
 View people in a workspace, granted by 1 team member
 Send messages on a user’s behalf, granted by 1 team member
 Upload, edit, and delete files on a user’s behalf, granted by 1 team member

### PR DESCRIPTION
**Pull request by kyteinsky**
fixes #8

- user icons in conversation list
- only show conversations user is part of

### CODE REVIEW

File: lib/Service/SlackAPIService.php [hunk 1]
```diff
@@ -118,21 +121,46 @@ private function getUserRealName(string $userId, string $slackUserId): ?string {
...
-		]);
-
-		if (isset($channelResult['error'])) {
-			return (array)$channelResult;
+	public function getMyChannels(string $userId, bool $useCache): array {
+		$dCache = $this->cacheFactory->createDistributed(Application::APP_ID);
+		$cacheKey = 'channels-' . $userId;
+
+		if (!$useCache) {
+			$dCache->remove($cacheKey);
```
Comment (julien-nc) [inline lib/Service/SlackAPIService.php:133]: Why invalidating the cache if the channels are requested without using the cache?
The cached value will be overwritten later in this method anyway.

Maybe you wanna make sure the cached value is cleared if the request fails. I don't think that's necessary, the TTL is enough.

IMO, those 2 lines can be removed.

File: lib/Service/SlackAPIService.php [hunk 2]
```diff
@@ -118,21 +121,46 @@ private function getUserRealName(string $userId, string $slackUserId): ?string {
...
+			$this->logger->debug('Slack channels cache hit', ['userId' => $userId]);
+			return $cachedChannels;
 		}
 
-		if (!isset($channelResult['channels']) || !is_array($channelResult['channels'])) {
-			return ['error' => 'No channels found'];
+		$cursor = 'dummdumm'; // initial value
+		$rawChannels = [];
+
+		while ($cursor !== '') {
```
Comment (julien-nc) [inline lib/Service/SlackAPIService.php:142]: We could try to make this a little bit safer:
* stop the loop if there are more than 10000 raw channels (or another relevant number)
* stop the loop if we think it is infinite: if the next_cursor is equal to the current cursor

**Review by julien-nc — CHANGES_REQUESTED** [review]

File: lib/Service/SlackAPIService.php (hunk 2 above)
Comment (julien-nc) [reply lib/Service/SlackAPIService.php]: Yeah and the MAX_CHANNELS_TO_FETCH will stop potential infinite loops anyway.
